name: Jira find release
description: Jira find release with filter parameters
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  projectKey:
    description: Jira project key case sensitive
    required: true
  prefix:
    description: Version prefix
    required: true
  status:
    description: Version status. (released, unreleased, archived)
    required: true
  order:
    description: Order direction, ordered by id. (asc, desc)
    required: true
outputs:
  version:
    description: Jira version object
runs:
  using: 'node16'
  main: './dist/index.js'
