name: Run jest tests

on: [ push ]

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: yarn install
      - name: Run tests
        run: yarn test
